/*
 * TinyFA
 * @author 	: keith@robot9.me
 *
 */

// This file is auto-generated by generate_kernels.py — do not edit manually.

#include "../launcher.cuh"

namespace tfa::impl {

// clang-format off

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 32
template void runFwd<SM8x, __half, 32, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 32, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 32, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 32, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 64
template void runFwd<SM8x, __half, 64, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 64, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 64, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 64, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 96
template void runFwd<SM8x, __half, 96, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 96, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 96, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 96, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 128
template void runFwd<SM8x, __half, 128, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 128, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 128, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 128, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 192
template void runFwd<SM8x, __half, 192, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 192, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 192, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 192, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 256
template void runFwd<SM8x, __half, 256, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM8x, __half, 256, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 256, false>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM8x, __half, 256, true>(
    const __half* Q, const __half* K, const __half* V, __half* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

// clang-format on

}  // namespace tfa::impl
