/*
 * TinyFA
 * @author 	: keith@robot9.me
 *
 */

// This file is auto-generated by generate_kernels.py — do not edit manually.

#include "../launcher.cuh"

namespace tfa::impl {

// clang-format off

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 32
template void runFwd<SM75, float, 32, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 32, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 32, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 32, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 64
template void runFwd<SM75, float, 64, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 64, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 64, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 64, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 96
template void runFwd<SM75, float, 96, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 96, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 96, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 96, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 128
template void runFwd<SM75, float, 128, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 128, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 128, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 128, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 192
template void runFwd<SM75, float, 192, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 192, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 192, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 192, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == 256
template void runFwd<SM75, float, 256, false>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<SM75, float, 256, true>(
    const float* Q, const float* K, const float* V, float* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 256, false>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<SM75, float, 256, true>(
    const float* Q, const float* K, const float* V, float* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif

// clang-format on

}  // namespace tfa::impl
