#!/usr/bin/env python3
from __future__ import annotations

"""
TinyFA — generate per-(SM, dtype) kernel instantiation .cu files.

Usage:
    python tools/generate_kernels.py                  # output to default dirs
    python tools/generate_kernels.py -o /path/to/dir  # custom output directory
"""

import argparse
from pathlib import Path

SM_TAGS = ["SM75", "SM80", "SM8x"]

DTYPE_MAP = {
    "fp32": "float",
    "fp16": "__half",
    "bf16": "__nv_bfloat16",
}

CONFIGS: dict[tuple[str, str], list[int]] = {}

for sm in SM_TAGS:
    CONFIGS[(sm, "fp32")] = [32, 64, 96, 128, 192, 256]
    CONFIGS[(sm, "fp16")] = [32, 64, 96, 128, 192, 256]
    CONFIGS[(sm, "bf16")] = [32, 64, 96, 128, 192, 256]


def _use_tensor_core(sm: str, dtype: str) -> bool:
    if dtype == "fp32":
        return False
    if sm in ("SM75",):
        return False
    return True


PRELUDE = """\
/*
 * TinyFA
 * @author 	: keith@robot9.me
 *
 */

// This file is auto-generated by generate_kernels.py — do not edit manually.
"""

INSTANTIATION_BLOCK = """\
#if !defined(TFA_TARGET_HEADDIM) || TFA_TARGET_HEADDIM == {head_dim}
template void runFwd<{sm_tag}, {dtype}, {head_dim}, false>(
    const {dtype}* Q, const {dtype}* K, const {dtype}* V, {dtype}* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwd<{sm_tag}, {dtype}, {head_dim}, true>(
    const {dtype}* Q, const {dtype}* K, const {dtype}* V, {dtype}* O,
    int batchSize, int seqLenQ, int seqLenKV, int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<{sm_tag}, {dtype}, {head_dim}, false>(
    const {dtype}* Q, const {dtype}* K, const {dtype}* V, {dtype}* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);

template void runFwdVarlen<{sm_tag}, {dtype}, {head_dim}, true>(
    const {dtype}* Q, const {dtype}* K, const {dtype}* V, {dtype}* O,
    const int* cuSeqLensQ, const int* cuSeqLensKV,
    int batchSize, int maxSeqLenQ, int maxSeqLenKV,
    int numHeadsQ, int numHeadsKV,
    cudaStream_t stream);
#endif
"""


def generate_cu_content(sm: str, dtype_key: str, head_dims: list[int]) -> str:
    dtype_cpp = DTYPE_MAP[dtype_key]
    blocks = []
    for hd in sorted(head_dims):
        blocks.append(INSTANTIATION_BLOCK.format(
            sm_tag=sm, dtype=dtype_cpp, head_dim=hd,
        ))

    return (
            f"{PRELUDE}\n"
            f"#include \"../launcher.cuh\"\n\n"
            f"namespace tfa::impl {{\n\n"
            f"// clang-format off\n\n"
            + "\n".join(blocks)
            + f"\n// clang-format on\n"
            + f"\n}}  // namespace tfa::impl\n"
    )


def make_filename(sm: str, dtype_key: str) -> str:
    sm_lower = sm.lower()  # SM80 -> sm80, SM8x -> sm8x
    return f"tfa_fwd_{dtype_key}_{sm_lower}.cu"


def main(output_dir: str | None) -> None:
    project_root = Path(__file__).parent.parent

    if output_dir is None:
        kernel_out = project_root / "csrc" / "flash_attn" / "kernels"
    else:
        kernel_out = Path(output_dir)

    kernel_out.mkdir(parents=True, exist_ok=True)

    kernel_files: list[str] = []

    for sm in SM_TAGS:
        for dtype_key in DTYPE_MAP:
            head_dims = CONFIGS.get((sm, dtype_key))
            if not head_dims:
                continue

            filename = make_filename(sm, dtype_key)
            content = generate_cu_content(sm, dtype_key, head_dims)
            (kernel_out / filename).write_text(content)
            kernel_files.append(filename)
            hdims_str = ", ".join(str(h) for h in sorted(head_dims))
            print(f"  Generated: kernels/{filename}  (HeadDims: {hdims_str})")

    print(f"\nTotal: {len(kernel_files)} kernel .cu files generated")

    # write cmake include snippet
    cmake_snippet = kernel_out / "kernel_sources.cmake"
    lines = [
        "#\n",
        "# TinyFA\n",
        "# @author 	: keith@robot9.me\n",
        "#\n",
        "#\n\n",
        "# Auto-generated by generate_kernels.py — do not edit manually.\n\n",
        "set(TFA_KERNEL_SOURCES\n",
    ]
    for f in sorted(kernel_files):
        lines.append(f"        ${{TFA_CSRC_DIR}}/flash_attn/kernels/{f}\n")
    lines.append(")\n")
    cmake_snippet.write_text("".join(lines))
    print(f"  Generated: kernels/kernel_sources.cmake")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="generate_kernels",
        description="Generate TinyFA per-(SM, dtype) kernel .cu files",
    )
    parser.add_argument(
        "-o", "--output_dir",
        required=False,
        help="Output directory (default: csrc/flash_attn/kernels/)",
    )
    args = parser.parse_args()
    main(args.output_dir)
